### ISSUE TITLE
How to add a EventHandler to network

### ISSUE THREAD

**Issue by coloeus** [lifeomic/react-vis-network#16]
Hello,
could you please provide an example how to add a Eventhandler to the network like:
`this.network.on("stabilizationIterationsDone",  () => {
        this.network.setOptions( { physics: false } );
        console.log(this.network.getSeed());
    });`

**Comment by B-R-Bender** [comment]
@coloeus did you find a way to do it right?

**Comment by jakubknejzlik** [comment]
@B-R-Bender Hi, maybe this could come in handy :)
https://codesandbox.io/s/1z3vk0xq63

**Comment by B-R-Bender** [comment]
thx @jakubknejzlik  did  exact the same :)
